name: telephony
description: A Flutter plugin to use telephony features such as send/receive sms and query telephony info
version: 0.2.0
homepage: https://github.com/shounakmulay/Telephony

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter